language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  # 'coveralls:report' goal is responsible for updating coverall.io stats once travisCI build completes
  # Look for the article 'Coveralls.io configuration for maven projects' in the wiki (https://github.com/asciidoctor/asciidoctor/wiki) for more details
  - mvn coveralls:report
