version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  MAVEN_VERSION: 3.3.9
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: |
      # If we run Java6 we install last Java6 compatible Maven
      if ($env:JAVA_HOME.EndsWith('jdk1.6.0')) {
        $env:MAVEN_VERSION = '3.2.5'
        $env:TESTS_OPTS = '-Dtest=AsciidoctorMojoTest,AsciidoctorMojoExtensionsTest,AsciidoctorHttpMojoTest,AsciidoctorZipMojoTest'
      }
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        Write-Host "Downloading Maven $env:MAVEN_VERSION"
        (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
  # Prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn -B -V -Prun-its clean verify %TESTS_OPTS%
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml